# Generated by Django 5.1 on 2024-08-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default=5, upload_to='images/'),
            preserve_default=False,
        ),
    ]
